apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-controller-deployment
  labels:
    app: test-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-controller
  template:
    metadata:
      labels:
        app: test-controller
    spec:
      containers:
      - name: test-controller
        image: public.ecr.aws/f8x3i1w1/test-controller:latest
        ports:
        - containerPort: 8080  # Adjust if test-controller uses a different port
        env:
        - name: CHROME_NODE_URL
          value: "http://chrome-node-service:4444"
---
apiVersion: v1
kind: Service
metadata:
  name: test-controller-service
spec:
  selector:
    app: test-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
